site_name: Spark Advanced Topics
plugins:
  - search
  - mermaid2:
      arguments:
        securityLevel: 'loose'
  - include-markdown

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid

copyright: Copyright various authors 2021, CC-BY-SA 4.0
